local: &default
  database_connection: "druby://0.0.0.0:2051"
  database:
    batch_size: 100_000
  crawler:
    agent: "lightblaze"
    threads: 100
    timeout: 10
    maxsize: 500_000
  robotstxt: # TODO Diesen Abschnitt eventuelln nochmals überarbeiten
    use_cache: YES
    cache_lifetime: 86400
  indexer:
    threads: 10
  paths:
    cache: "/mnt/sdb/suchmaschine/cache/"
    document: "/home/lightblaze/suchmaschine/db/document/"
    download_queue: "/home/lightblaze/suchmaschine/db/download_q/"
    index_queue: "/home/lightblaze/suchmaschine/db/index_q/"
    postings: "/mnt/sdb/suchmaschine/postings/"
    postings_metadata: "/mnt/sdb/suchmaschine/postings_metadata/"
    postings_metadata_temporary: "/mnt/sdb/suchmaschine/postings_metadata_temporary/"
    postings_temporary: "/mnt/sdb/suchmaschine/indextmp/"
    metadata: "/mnt/sdb/suchmaschine/metadata/"

wired:
  <<: *default
  database_connection: "druby://192.168.10.50:2051"

wireless:
  <<: *default
  database_connection: "druby://192.168.1.106:2051"

offline-laptop:
  <<: *default
  paths:
    cache: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/cache/"
    document: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/document/"
    download_queue: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/download_q/"
    index_queue: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/index_q/"
    postings: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/postings/"
    postings_metadata: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/postings_metadata/"
    postings_metadata_temporary: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/postings_metadata_temporary/"
    postings_temporary: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/indextmp/"
    metadata: "/Users/leonardo.schwarz/Desktop/suchmaschine/db/metadata/"

offline-desktop:
  <<: *default
  paths:
    cache: "/Users/leoschwarz/Desktop/suchmaschine/db/cache/"
    document: "/Users/leoschwarz/Desktop/suchmaschine/db/document/"
    download_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/download_q/"
    index_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/index_q/"
    postings: "/Users/leoschwarz/Desktop/suchmaschine/db/postings/"
    postings_metadata: "/Users/leoschwarz/Desktop/suchmaschine/db/postings_metadata/"
    postings_metadata_temporary: "/Users/leoschwarz/Desktop/suchmaschine/db/postings_metadata_temporary/"
    postings_temporary: "/Users/leoschwarz/Desktop/suchmaschine/db/indextmp/"
    metadata: "/Users/leoschwarz/Desktop/suchmaschine/db/metadata/"
