local: &default
  database_connection: "druby://0.0.0.0:2051"
  database:
    batch_size: 100_000
    block_size: # Angaben in KB
      document: 128
      metadata: 4
      cache: 4
      search_cache: 4
      postings_block: 32
      postings_metadata: 8
    client_whitelist:
      - 127.0.0.1
      - 192.168.10.100
  crawler:
    agent: "lightblaze"
    threads: 100
    timeout: 10
    maxsize: 500_000
  robotstxt:
    cache:
      enabled: YES
      lifetime: 86400
  indexer:
    threads: 10
  paths:
    cache: "/mnt/sdb/suchmaschine/cache/"
    search_cache: "/mnt/sdb/suchmaschine/search_cache/"
    document: "/home/lightblaze/suchmaschine/db/document/"
    download_queue: "/home/lightblaze/suchmaschine/db/download_q/"
    index_queue: "/home/lightblaze/suchmaschine/db/index_q/"
    postings_block: "/mnt/sdb/suchmaschine/postings/"
    postings_metadata: "/mnt/sdb/suchmaschine/postings_metadata/"
    metadata: "/mnt/sdb/suchmaschine/metadata/"

wired:
  <<: *default
  database_connection: "druby://192.168.10.50:2051"

wireless:
  <<: *default
  database_connection: "druby://192.168.1.106:2051"

offline-laptop:
  <<: *default
  paths:
    cache: "/Users/leonardo.schwarz/Maturarbeit/Code/db/cache/"
    search_cache: "/Users/leonardo.schwarz/Maturarbeit/Code/db/search_cache/"
    document: "/Users/leonardo.schwarz/Maturarbeit/Code/db/document/"
    download_queue: "/Users/leonardo.schwarz/Maturarbeit/Code/db/download_q/"
    index_queue: "/Users/leonardo.schwarz/Maturarbeit/Code/db/index_q/"
    postings_block: "/Users/leonardo.schwarz/Maturarbeit/Code/db/postings/"
    postings_metadata: "/Users/leonardo.schwarz/Maturarbeit/Code/db/postings_metadata/"
    metadata: "/Users/leonardo.schwarz/Maturarbeit/Code/db/metadata/"

offline-desktop:
  <<: *default
  paths:
    cache: "/Users/leoschwarz/Desktop/suchmaschine/db/cache/"
    search_cache: "/Users/leoschwarz/Desktop/suchmaschine/db/search_cache/"
    document: "/Users/leoschwarz/Desktop/suchmaschine/db/document/"
    download_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/download_q/"
    index_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/index_q/"
    postings_block: "/Users/leoschwarz/Desktop/suchmaschine/db/postings/"
    postings_metadata: "/Users/leoschwarz/Desktop/suchmaschine/db/postings_metadata/"
    metadata: "/Users/leoschwarz/Desktop/suchmaschine/db/metadata/"
