production: &default
  database:
    host: "127.0.0.1"
    port: 2051

development:
  <<: *default
  database:
    host: "192.168.10.50"
    port: 2051

laptop:
  <<: *default
  database:
    host: "192.168.1.106"
    port: 2051

test:
  <<: *default
