production: &default
  task_queue_size: 100   # Anzahl der Aufgaben in der Memory-Warteschleife
  parallel_tasks: 10     # Anzahl paralleler Downloads
  user_agent: lightblaze # Name des USER_AGENT Felds für HTTP Requests
  crawl_delay: 1.0       # Anzahl Sekunden die gewartet werden muss bevor von der gleichen Domain wieder etwas geladen werden darf.
  redis: "redis://127.0.0.1:6379"
  database:
    connections: 20
    name: suchmaschine
    host: 127.0.0.1
    user: leo
    password: 1234
  robots_txt:
    timeout: 10 # Sekunden
    use_cache: YES
    cache_lifetime: 86400 # Sekunden, hier ein Tag.

development:
  <<: *default
  redis: "redis://192.168.1.110:6379"
  database:
    connections: 20
    name: suchmaschine
    host: 192.168.1.110
    user: leo
    password: 1234

test:
  <<: *default
  robots_txt:
    timeout: 10
    use_cache: NO
    cache_lifetime: 0
