############################################################################################
# Haupt-Konfiguration der Suchmaschine                                                     #
############################################################################################

local: &default
  # Verbindung zur Datenbank, "druby://0.0.0.0:2051" bedeutet lokal.
  database_connection: "druby://0.0.0.0:2051"
  # Parameter der Datenbank
  database:
    # Grösse eines BetterQueue-Stapels in Anzahl Zeilen.
    batch_size: 100_000
    # Blockgrössen der verschiedenen LevelDB Datenbanken in KB.
    block_size:
      document: 128
      metadata: 4
      cache: 4
      search_cache: 4
      postings_block: 32
      postings_metadata: 8
    # Whitelist der erlaubten IPs, welche eine Verbindung zur Datenbank herstellen dürfen.
    client_whitelist:
      - 127.0.0.1
      - 192.168.10.100
  # Parameter des Crawlers
  crawler:
    # User-Agent der bei HTTP-Anfragen mitgesendet werden soll.
    agent: "breaksearch.crawler/1.0"
    # Anzahl Threads, die für das Crawling verwendet werden sollen.
    threads: 100
    # Timeout von HTTP-Anfragen in Sekunden.
    # Sollte eine Anfrage länger dauern, wird sie als Fehler abgebgrochen.
    timeout: 10
    # Maximale Grösse einer HTTP-Antwort in Bytes.
    # Überschüssiger Inhalt wird abgetrennt und nicht empfangen.
    maxsize: 500_000
  # Konfiguration des robots.txt-Lesers
  robotstxt:
    cache:
      # Cache aktiviert?
      enabled: YES
      # Maximales Alter von Cache-Einträgen in Sekunden.
      lifetime: 86400
  # Konfiguration des Indexierers.
  indexer:
    # Anzahl Threads, die für die Indexierung verwendet werden sollen.
    threads: 20
  # Konfiguration der Dateipfade für die Speicherung der Daten.
  # Ordner müssen mit einem Slash beendet werden.
  paths:
    # Pfad zum Ordner in dem die Cache-Einträge gespeichert werden.
    cache: "/mnt/sdb/suchmaschine/cache/"
    # Pfad zum Ordner in dem die Dokumente gespeichert werden.
    document: "/home/lightblaze/suchmaschine/db/document/"
    # Pfad zum Ordner in dem die Download-Warteschlange gespeichert wird.
    download_queue: "/home/lightblaze/suchmaschine/db/download_q/"
    # Pfad zur Index-Datei.
    index: "/mnt/sdb/suchmaschine/index"
    # Pfad zum Ordner in dem die temporären Index-Dateien gespeichert werden.
    index_tmp: "/home/lightblaze/suchmaschine/tmp/index/"
    # Pfad zum Ordner in dem die Index-Warteschlange gespeichert wird.
    index_queue: "/home/lightblaze/suchmaschine/db/index_q/"
    # Pfad zum Ordner in dem die Metadaten gespeichert werden.
    metadata: "/mnt/sdb/suchmaschine/metadata/"
    # Pfad zum Ordner in dem die SearchCache-Einträge gespeichert werden.
    search_cache: "/mnt/sdb/suchmaschine/search_cache/"

# Es folgen noch einige weitere beispiele von Profilen, welche bei der
# Entwicklung der Suchmaschine verwendet wurden.
wired:
  <<: *default
  database_connection: "druby://192.168.10.50:2051"

wireless:
  <<: *default
  database_connection: "druby://192.168.1.106:2051"

offline-laptop:
  <<: *default
  paths:
    cache: "/Users/leonardo.schwarz/Maturarbeit/Code/db/cache/"
    search_cache: "/Users/leonardo.schwarz/Maturarbeit/Code/db/search_cache/"
    document: "/Users/leonardo.schwarz/Maturarbeit/Code/db/document/"
    download_queue: "/Users/leonardo.schwarz/Maturarbeit/Code/db/download_q/"
    index: "/Users/leonardo.schwarz/Maturarbeit/Code/db/index"
    index_tmp: "/Users/leonardo.schwarz/Maturarbeit/Code/tmp/index/"
    index_queue: "/Users/leonardo.schwarz/Maturarbeit/Code/db/index_q/"
    metadata: "/Users/leonardo.schwarz/Maturarbeit/Code/db/metadata/"

offline-desktop:
  <<: *default
  paths:
    cache: "/Users/leoschwarz/Desktop/suchmaschine/db/cache/"
    search_cache: "/Users/leoschwarz/Desktop/suchmaschine/db/search_cache/"
    document: "/Users/leoschwarz/Desktop/suchmaschine/db/document/"
    download_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/download_q/"
    index: "/Users/leoschwarz/Desktop/suchmaschine/db/index"
    index_tmp: "/Users/leoschwarz/Desktop/suchmaschine/tmp/index/"
    index_queue: "/Users/leoschwarz/Desktop/suchmaschine/db/index_q/"
    metadata: "/Users/leoschwarz/Desktop/suchmaschine/db/metadata/"
