production: &default
  parallel_tasks: 100    # Anzahl paralleler Downloads
  user_agent: lightblaze # Name des USER_AGENT Felds für HTTP Requests
  max_response_length: 512000 # 1024 * 500 Bytes, also 500kB
  crawl_delay: 1.0       # Anzahl Sekunden die gewartet werden muss bevor von der gleichen Domain wieder etwas geladen werden darf.
  log_interval: 5        # Anzahl Sekunden zwischen den Logs
  robots_txt:
    timeout: 10 # Sekunden
    use_cache: YES
    cache_lifetime: 86400 # Sekunden, hier ein Tag.
  database:
    host: "127.0.0.1"
    port: 2051

development:
  <<: *default
  database:
    host: "192.168.10.50"
    port: 2051

test:
  <<: *default
  robots_txt:
    timeout: 10
    use_cache: NO
    cache_lifetime: 0
