production: &default
  ssd:
    path: "/mnt/sdb/suchmaschine/"
    max_size: 10_000_000_000 # Bytes
  hdd:
    path: "./db/keyval/"
    max_size: 20_000_000_000 # Bytes
  task_queue:
    max_active: 100_000 # Die maximale Anzahl an Einträgen die im RAM gehalten werden soll.
    storage_path: "db/task_queue.log"
    storage_buffer: 500 # Die Anzahl Transaktionen die im RAM bleiben soll bevor sie geschrieben werden. 

development:
  <<: *default

test:
  <<: *default
