production: &default
  ssd:
    path: "/mnt/sdb/suchmaschine/"
    max_size: 10_000_000_000 # Bytes
  hdd:
    path: "./db/keyval/"
    max_size: 20_000_000_000 # Bytes
  batch_size: 200_000
  download_queue:
    directory: './db/urls/'
  index_queue:
    directory: './db/index/'
  server:
    host: "0.0.0.0"
    port: 2051

development:
  <<: *default

test:
  <<: *default
