production: &default
  ssd:
    path: "/mnt/sdb/suchmaschine/"
    max_size: 10_000_000_000 # Bytes
  hdd:
    path: "./db/keyval/"
    max_size: 20_000_000_000 # Bytes
  url_storage:
    directory: './db/urls/'
    batch_size: 100_000
  server:
    host: "0.0.0.0"
    port: 2051

development:
  <<: *default

test:
  <<: *default
