production: &default
  max_size: 100_000  # Die maximale Anzahl an Eintr채gen die im RAM gehalten werden soll.
  save_to_disk: YES  # Sollen 체bersch체ssige Eintr채ge und alle Operationen niedergeschrieben werden.

development:
  <<: *default

test:
  <<: *default
